sudo: false
language: node_js
node_js:
  - "0.12"
  # NB this should be 4.2, which is the LTS for node; they are working on it.
  - "4.1"
cache:
  directories:
  - bower_components
  - node_modules
branches:
    only:
        - master
        
        
#branches:
#  only:
#    - develop
#    - staging
#    - master
#before_install:
#  - npm install -g bower
#  - npm install -g grunt-cli
install:
  - make build config=ci
script: make test-travis