## Global Build Config
---
targets:
    ui: prod
    deploy: next
build:
    dist: false
    temp: ../temp
bower:
    offline: false
debug: false
server:
    port: 8080
features:
    auth:
        selected: auth2
