## Global Build Config
---
targets:
    ui: dev
    deploy: ci
build:
    dist: true
    temp: ../temp
bower:
    offline: false
debug: false
server:
    port: 8080
features:
    auth:
        selected: auth2
