# UI SErvices
---
ui:
  services:
    heartbeat: {}
    widget: {}
    data: {}
    type: {}
    userprofile: {}
    analytics: {}
    ko-component: {}
    notification: {}
    schema: {}
    route: {}
    session: {}
    rpc: {}
    # dynamic-service: {}
    menu:
      menus:
        hamburger:
          sections:
            main:
              items:
                -
                  id: narrative
                  auth: true
                -
                  id: jgi-search
                  auth: true
            developer:
              items:
                -
                  id: about-services
                  auth: true
                  allowRoles: [DevToken]
                -
                  id: simple-search
                  auth: true           
                  allowRoles: [DevToken]
                -
                  id: narrative-info
                  auth: true
                  allow: [alpha]
                -
                  id: reske-admin
                  auth: true
                  allow: [alpha]
                -
                  id: dashboard2
                  auth: true
                  allow: [alpha]
                  allowRoles: [DevToken]                  
            help:
              items:
                -
                  id: about
                  auth: false
                -
                  id: contact-kbase
                  auth: false
                -
                  id: help
                  auth: false
        sidebar:
          sections:
            main:
              items:
                -
                  id: dashboard
                  auth: true
                -
                  id: appcatalog
                  auth: false
                -
                  id: search
                  auth: true
                -
                  id: jobbrowser
                  # The label can ovveride the label from the plugin here
                  label: Jobs
                  auth: true
                -
                  id: account
                  auth: true
                -
                  id: feeds
                  auth: true
                  allow: [alpha]
