## Build Configuration
---
plugins:
    # Plugins which come-with kbase-ui
    -
        mainwindow
    -
        message
    -
        welcome
    -
         name: login
         internal: true
         disabled: true
    -
        datasearch
    -
        narrativemanager
    -
        catalog
    -
        about
    # external:
    # These are shared with production
    -
        name: viswidgets
        globalName: kbase-ui-plugin-vis-widgets
        cwd: src/plugin
        version: 1.2.0
        source:
            bower: {}
    -
        name: typeview
        globalName: kbase-ui-plugin-typeview
        cwd: src/plugin
        version: 1.1.1
        source:
            bower: {}
    -
        name: dataview
        globalName: kbase-ui-plugin-dataview
        version: 3.1.2
        cwd: src/plugin
        source:
            bower: {}
    -
        name: dashboard
        globalName: kbase-ui-plugin-dashboard
        version: 2.1.4
        cwd: src/plugin
        source:
            bower: {}
    # These are just developer
    # -
    #     name: viswidgetdemo
    #     globalName: kbase-ui-plugin-demo-vis-widget
    #     cwd: src/plugin
    #     version: 1.0.0
    #     source:
    #         bower: {}
    -
        name: databrowser
        globalName: kbase-ui-plugin-databrowser
        version: 1.0.1
        cwd: src/plugin
        source:
            bower: {}
    -
        name: typebrowser
        globalName: kbase-ui-plugin-typebrowser
        version: 1.0.2
        cwd: src/plugin
        source:
            bower: {}
    -
        name: datawidgets
        globalName: kbase-ui-plugin-datawidgets
        version: 0.4.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: data-landing-pages
        globalName: kbase-ui-plugin-data-landing-pages
        version: 0.7.3
        cwd: src/plugin
        source:
            bower: {}
    -
        name: shockbrowser
        globalName: kbase-ui-plugin-shockbrowser
        version: 0.2.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: jobbrowser
        globalName: kbase-ui-plugin-jobbrowser
        version: 0.2.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: methodview
        globalName: kbase-ui-plugin-methodview
        version: 1.1.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: ontology-widgets
        globalName: kbase-ui-plugin-ontology-widgets
        version: 1.0.3
        cwd: src/plugin
        source:
            bower: {}
    -
        name: sdk-clients-test
        globalName: kbase-ui-plugin-sdk-clients-test
        version: 0.1.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: bulk-ui
        globalName: kbase-ui-plugin-bulk-ui
        version: 0.4.0
        cwd: src/plugin
        source:
            bower: {}
    -
        name: auth2-client
        disabled: true
        globalName: kbase-ui-plugin-auth2-client
        version: 0.10.1
        cwd: src/plugin
        source:
            bower: {}
    -
        name: user-profile
        globalName: kbase-ui-plugin-user-profile
        version: 1.0.4
        cwd: src/plugin
        source:
            bower: {}


# Copy these directories into the modules
# There are two forms, as for plugins.
# a bower: section will specify a bower dependency
# a copy: section will specify a directory to copy literally into modules
# a link: section will specify a directory to link into modules

modules: []
