## Plugin Build Configuration
---
plugins:
  # Plugins which come-with kbase-ui
  - welcome
  - narrativemanager
  - about
  - developer
  # external:
  - name: typeview
    globalName: kbase-ui-plugin-typeview
    version: 3.0.0
    source:
      github:
        account: kbase
  - name: dataview
    globalName: kbase-ui-plugin-dataview
    version: 4.7.12
    source:
      github:
        account: kbase
  - name: dashboard
    globalName: kbase-ui-plugin-dashboard
    version: 4.0.2
    source:
      github:
        account: kbase
  - name: auth2-client
    globalName: kbase-ui-plugin-auth2-client
    version: 2.3.20
    source:
      github:
        account: kbase
  - name: jgi-search
    globalName: kbase-ui-plugin-jgi-search
    version: 2.0.0
    source:
      github:
        account: kbase
  - name: feeds
    globalName: kbase-ui-plugin-feeds
    version: 2.0.0
    source:
      github:
        account: kbase
  - name: catalog
    globalName: kbase-ui-plugin-catalog
    version: 2.2.1
    source:
      github:
        account: kbase
  - name: data-search
    globalName: kbase-ui-plugin-data-search
    version: 2.0.0
    source:
      github:
        account: kbase
  - name: organizations
    globalName: kbase-ui-plugin-organizations
    version: 2.1.2
    source:
      github:
        account: kbase
  - name: biochem-search
    globalName: kbase-ui-plugin-biochem-search
    version: 2.1.0
    source:
      github:
        account: kbase
  - name: job-browser2
    globalName: kbase-ui-plugin-job-browser2
    version: 1.5.16
    source:
      github:
        account: kbase
  - name: react-profile-view
    globalName: kbase-ui-plugin-react-profile-view
    version: 1.2.10
    source:
      github:
        account: kbaseIncubator
  - name: re-landing-pages
    globalName: kbase-ui-plugin-re-landing-pages
    version: 0.10.1
    source:
      github:
        account: kbaseIncubator
  - name: dashboard4
    globalName: kbase-ui-plugin-dashboard4
    version: 0.2.0
    source:
      github:
        account: eapearson
  - name: sampleview
    globalName: kbase-ui-plugin-sampleview
    version: 0.7.10
    source:
      github:
        account: kbaseIncubator
  - name: ontology
    globalName: kbase-ui-plugin-ontology
    version: 0.1.9
    source:
      github:
        account: kbaseIncubator
  - name: taxonomy
    globalName: kbase-ui-plugin-taxonomy
    version: 0.1.1
    source:
      github:
        account: kbaseIncubator
  # The following have not been ported (yet if ever)
  # Unreleased
  # - name: public-search
  #   globalName: kbase-ui-plugin-public-search
  #   version: 0.13.6
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # Experimental or Dev Only
  # - name: ui-service
  #   globalName: kbase-ui-plugin-ui-service
  #   version: 0.5.0
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # - name: dashboard2
  #   globalName: kbase-ui-plugin-dashboard2
  #   version: 0.2.2
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # - name: narrative-finder
  #   globalName: kbase-ui-plugin-narrative-finder
  #   version: 0.1.2
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # - name: example-hello
  #   globalName: kbase-ui-plugin-example-hello
  #   version: 0.1.5
  #   cwd: plugin
  #   source:
  #       github:
  #           account: kbaseIncubator
  # - name: narrative-info
  #   globalName: kbase-ui-plugin-narrative-info
  #   version: 1.1.4
  #   cwd: src/plugin
  #   source:
  #     bower: {}
