## Plugin Build Configuration
---
plugins:
  # Plugins which come-with kbase-ui
  - mainwindow
  - welcome
  - narrativemanager
  - about
  - login
  # external:
  - name: typeview
    globalName: kbase-ui-plugin-typeview
    version: 2.0.0
    source:
      bower: {}
  - name: dataview
    globalName: kbase-ui-plugin-dataview
    version: 4.4.10
    source:
      git: {}
  - name: dashboard
    globalName: kbase-ui-plugin-dashboard
    version: 3.2.1
    source:
      bower: {}
  - name: auth2-client
    globalName: kbase-ui-plugin-auth2-client
    version: 2.2.3
    source:
      bower: {}
  - name: jgi-search
    globalName: kbase-ui-plugin-jgi-search
    version: 1.0.0
    source:
      bower: {}
  - name: feeds
    globalName: kbase-ui-plugin-feeds
    version: 1.1.1
    source:
      bower: {}
  - name: catalog
    globalName: kbase-ui-plugin-catalog
    version: 2.1.4
    source:
      bower: {}
  - name: data-search
    globalName: kbase-ui-plugin-data-search
    version: 1.1.0
    source:
      bower: {}
  - name: organizations
    globalName: kbase-ui-plugin-organizations
    version: 1.0.0
    cwd: src/plugin
    source:
      git: {}
  - name: biochem-search
    globalName: kbase-ui-plugin-biochem-search
    version: 2.0.4
    source:
      git: {}
  - name: job-browser2
    globalName: kbase-ui-plugin-job-browser2
    version: 1.1.4
    source:
      git: {}
  - name: react-profile-view
    globalName: kbase-ui-plugin-react-profile-view
    version: 1.2.6
    source:
      git:
        account: kbaseIncubator
  - name: re-landing-pages
    globalName: kbase-ui-plugin-re-landing-pages
    version: 0.6.2
    source:
      git:
        account: kbaseIncubator
  - name: dashboard4
    globalName: kbase-ui-plugin-dashboard4
    version: 0.1.4
    source:
      git:
        account: eapearson
  # Unreleased
  # - name: public-search
  #   globalName: kbase-ui-plugin-public-search
  #   version: 0.13.6
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # Experimental or Dev Only
  # - name: ui-service
  #   globalName: kbase-ui-plugin-ui-service
  #   version: 0.5.0
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # - name: dashboard2
  #   globalName: kbase-ui-plugin-dashboard2
  #   version: 0.2.2
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # - name: narrative-finder
  #   globalName: kbase-ui-plugin-narrative-finder
  #   version: 0.1.2
  #   cwd: src/plugin
  #   source:
  #     bower: {}
  # - name: example-hello
  #   globalName: kbase-ui-plugin-example-hello
  #   version: 0.1.5
  #   cwd: plugin
  #   source:
  #       git:
  #           account: kbaseIncubator
  # - name: narrative-info
  #   globalName: kbase-ui-plugin-narrative-info
  #   version: 1.1.4
  #   cwd: src/plugin
  #   source:
  #     bower: {}
