## KBase UI Configuration
---
# TODO: ensure that this list includes all supported services
# TODO: ensure that all services represented are also defined as amd modules
# TODO: alpha sort of services
# TODO: switch to deployment-friendly configuration
services:
    awe:
        url: '{{ deploy.services.urlBase }}/services/awe-api'
        name: AWE
    data_import_export:
        url: '{{ deploy.services.urlBase }}/services/data_import_export'
        name: Data Import Export
    fba:
        url: https://kbase.us/services/KBaseFBAModeling
        name: FBA
    narrative_method_store:
        url: '{{ deploy.services.urlBase }}/services/narrative_method_store/rpc'
        image_url: '{{ deploy.services.urlBase }}/services/narrative_method_store/'
        name: Narrative Method Store
    search:
        url: https://kbase.us/services/search/
        name: Data Search
    shock: 
        url: '{{ deploy.services.urlBase }}/services/shock-api'
        name: Shock
    user_profile:
        url: '{{ deploy.services.urlBase }}/services/user_profile/rpc'
        name: User Profile
    user_job_state:
        url: '{{ deploy.services.urlBase }}/services/userandjobstate'
        name: User and Job State
    narrative_job_service:
        url: '{{ deploy.services.urlBase }}/services/njs_wrapper'
        name: Narrative Job Service
    workspace:
        url: '{{ deploy.services.urlBase }}/services/ws'
        name: Workspace    
    narrative:
        url: '{{ deploy.services.urlBase }}'
        name: Narrative User Interface    
    catalog:
        url: '{{ deploy.services.urlBase }}/services/catalog'
        name: Catalog
    service_wizard:
        url: '{{ deploy.services.urlBase }}/services/service_wizard'
        name: Service Wizard
    ftp:
        url: '{{ deploy.services.urlBase }}/services/kb-ftp-api/v0'
        root: /data/bulk
        name: FTP Service
    auth2:
        url: '{{ deploy.services.urlBase }}/services/auth'
        cookieName: kbase_session
        name: Authorization Version 2
    doc_site:
        url: http://kbase.us
        name: Documentation and Support Site
    reske:
        url: '{{ deploy.services.urlBase }}/services/reske'
        name: Search Two
    # jgi_gateway_eap:
    #     url: '{{ deploy.services.urlBase }}/devservices/jgi_gateway_clj/rpc'        
resources:
    docSite:
        base:
            url: http://kbase.us
    documentation:
        loginHelp:
            url: http://kbase.us/help
        narrativeGuide:
            url: http://kbase.us/narrative-guide
        tutorials:
            url: http://kbase.us/tutorials
        apps:
            url: http://kbase.us/apps
        troubleshooting:
            signin: http://kbase.us/troubleshooting/sign-in
    userAccount:
        resetPassword: 
            url: http://kbase.us/reset-password
        updateProfile: 
            url: https://www.globusid.org/profile
        update_profile: 
            url: https://www.globusid.org/profile
        access:
            url: https://gologin.kbase.us/globus-app/account
        signUp:
            url: http://kbase.us/sign-up
    contact:
        url: http://kbase.us/contact-us
        name: Contact KBase
    status_page:  http://kbase.us/internal/status
    submit_jira_ticket: https://atlassian.kbase.us/secure/CreateIssueDetails!init.jspa?pid=10200&issuetype=1&description=#Narrative%
