## Build Configuration
---
plugins:
    # Plugins which come-with kbase-ui
    -
        mainwindow
    -
        message
    -
        welcome
    -
        login
    -
        userprofile
    -
        datasearch
    -
        narrativemanager
    -
        catalog
    -
        narrativestore
    # external:
    -
        name: viswidgets
        globalName: kbase-ui-plugin-vis-widgets
        cwd: src/plugin
        version: 0.1.1
        source:
            bower: {}
    -
        name: typeview
        globalName: kbase-ui-plugin-typeview
        cwd: src/plugin
        version: 0.1.2
        source:
            bower: {}
    -
        name: dataview
        globalName: kbase-ui-plugin-dataview
        version: 0.1.3
        cwd: src/plugin
        source:
            bower: {}
    -
        name: dashboard
        globalName: kbase-ui-plugin-dashboard
        version: 0.1.1
        cwd: src/plugin
        source:
            bower: {}

               
# Copy these directories into the modules
# There are two forms, as for plugins. 
# a bower: section will specify a bower dependency
# a copy: section will specify a directory to copy literally into modules
# a link: section will specify a directory to link into modules

modules:
    -
        globalName: kbase-ui-widget
        version: 0.1.4
        source:
            bower: {}
    -
        globalName: kbase-common-js
        version: 0.1.3
        source:
            bower: {}
    -
        globalName: kbase-service-clients-js
        version: 0.1.5
        source:
            bower: {}
    -
        globalName: kbase-data-api-js-clients
        version: 0.1.7
        source:
            bower: {}