# Settings in support of the user interface
ui:
    images:
        spinner:
            url: /images/ajax-loader.gif  
    constants:
        client_timeout: 900000,
        session_max_age: 5184000
     # TODO: simply paths?    
    paths:
        spa_root: '#'
        landing_pages: '#dataview/'
        # ws_browser: '#/ws'
        version_check: /narrative_version
        dashboard_metrics: /userMetrics
    # TODO: simply urls?
    urls:
        reset_password: https://gologin.kbase.us/ResetPassword
        status_page: http://kbase.us/internal/status
        submit_jira_ticket: https://atlassian.kbase.us/secure/CreateIssueDetails!init.jspa?pid=10200&issuetype=1&description=#Narrative%20version
        update_profile: https://gologin.kbase.us/account/UpdateProfile
        
# Primarily for output links for the docsite. 
# TODO: merge with ui.outbound_links?        
docsite:
    base_url: http://kbase.us
    host: kbase.us
    paths:
        about: /what-is-kbase
        contact: /contact-us
        browser_support: /supported-browsers

menus:
    authenticated: 
        main: [narrative, appcatalog, search, dashboard, bulk-ui]
        developer: []
        help: [contact-kbase, about-kbase, help]
    unauthenticated: 
        main: [appcatalog, search]
        developer: []
        help: [contact-kbase, about-kbase, help]
