## KBase UI Configuration
---
# TODO: ensure that this list includes all supported services
# TODO: ensure that all services represented are also defined as amd modules
# TODO: alpha sort of services
# TODO: switch to deployment-friendly configuration
services:
    awe:
        url: <%= awe_url %>
        name: AWE
    cdmi:
        url: <%= cdmi_url %>
        name: CDMI
    data_import_export:
        url: <%= data_io_url %>
        name: Data Import Export
    fba:
        url: <%= fba_url %>
        name: FBA
    gene_families:
        url: <%= gene_families_url %>
        name: Gene Families
    genome_comparison:
        url: <%= genome_comparison_url %>
        name: Genome Comparison
    narrative_method_store:
        url: <%= nms_url %>
        image_url: <%= nms_image_url %>
        name: Narrative Method Store
    search:
        url: <%= search_url %>
        name: Data Search
    shock: 
        url: <%= shock_url %>
        name: Shock
    transform:
        url: <%= transform_url %>
        name: Transform
    trees:
        url: <%= trees_url %>
        name: Trees
    user_profile:
        url: <%= user_profile_url %>
        name: User Profile
    user_job_state:
        url: <%= ujs_url %>
        name: User and Job State
    workspace:
        url: <%= ws_url %>
        name: Workspace    
    narrative:
        url: <%= narrative_url %>
        name: Narrative User Interface    
    catalog:
        url: <%= catalog_url %>
        name: Catalog
    doc_site:
        url: <%= doc_site_url %>
        name: Documentation and Support Site
    service_wizard:
        url: <%= service_wizard_url %>
        name: Service Wizard
    narrative_job_service:
        url: <%= njs_url %>
        name: Narrative Job Service
    ftp:
        url: <%= ftp_api_url %>
        root: <%= ftp_api_root %>
        name: FTP Service
    auth2:
        url: <%= auth2_url %>
        cookieName: <%= auth2_cookie_name %>
        name: Authorization Version 2
        
resources:
    docSite:
        base:
            url: <%= doc_site_url %>
    documentation:
        loginHelp:
            url: <%= doc_login_help %>
        narrativeGuide:
            url: <%= doc_narrative_guide %>
        tutorials:
            url: <%= doc_tutorials %>
        apps:
            url: <%= doc_apps %>
    userAccount:
        resetPassword: 
            url: <%= reset_password_url %>
        updateProfile: 
            url: <%= update_profile_url %> 
        update_profile: 
            url: <%= update_profile_url %> 
        access:
            url: <%= user_account_url %>
        signUp:
            url: <%= signup_url %>
    contact:
        url: <%= contact_url %>
        name: Contact KBase
    status_page: <%= status_page_url %>
    submit_jira_ticket: <%= submit_jira_ticket_url %>
    googleAnalytics:
        code: <%= google_analytics_code %>
deploy:
    environment: <%= deploy_environment %>
    hostname: <%= deploy_hostname %>
    icon: <%= deploy_icon %>
    name: <%= deploy_name %>
    cookie-domain: <%= deploy_cookie_domain %>
    backup-cookie-enabled: <%= deploy_backup_cookie_enabled %>