menus:
    authenticated:
        main: [narrative, bulk-ui]
        developer: [staging-browser, example-gopherjs, reske-admin, reske-object-search,jgi-search, tester, test_dynamic_table, paveldemo, sdkclientstest, databrowser, typebrowser, jobbrowser, shockbrowser]
        help: [about, about-services, contact-kbase, help]
        # TODO: congigurable sidebar menu items
        # sidebar: [dashboard, catalog, account, reske-narrative-search]
    unauthenticated:
        main: []
        developer: []
        help: [about, contact-kbase, help]
        # TODO: congigurable sidebar menu items
        # sidebar: [catalog]
