menus:
    authenticated:
        main: [narrative, bulk-ui]
        developer: [simple-sample, narrative-finder, staging-browser,  example-gopherjs, reske-admin, reske-object-search,jgi-search, tester, test_dynamic_table, paveldemo, sdkclientstest, databrowser, typebrowser,  shockbrowser]
        help: [about, about-services, contact-kbase, help]
        # TODO: congigurable sidebar menu items
        # sidebar: [dashboard, catalog, account, reske-narrative-search]
    unauthenticated:
        main: []
        developer: []
        help: [about, contact-kbase, help]
        # TODO: congigurable sidebar menu items
        # sidebar: [catalog]
