## Build Configuration
---
plugins:
  # Plugins which come-with kbase-ui
  - components
  - mainwindow
  - message
  - welcome
  - narrativemanager
  - about
  # external:
  # These are shared with production
  - name: viswidgets
    globalName: kbase-ui-plugin-vis-widgets
    cwd: src/plugin
    version: 1.2.0
    source:
      bower: {}
  - name: typeview
    globalName: kbase-ui-plugin-typeview
    cwd: src/plugin
    version: 1.3.0
    source:
      bower: {}
  - name: dataview
    globalName: kbase-ui-plugin-dataview
    version: 3.11.2
    cwd: src/plugin
    source:
      bower: {}
  - name: dashboard
    globalName: kbase-ui-plugin-dashboard
    version: 2.5.4
    cwd: src/plugin
    source:
      bower: {}
  - name: dashboard2
    globalName: kbase-ui-plugin-dashboard2
    version: 0.2.2
    cwd: src/plugin
    source:
      bower: {}

  # These are just developer
  # -
  #     name: viswidgetdemo
  #     globalName: kbase-ui-plugin-demo-vis-widget
  #     cwd: src/plugin
  #     version: 1.0.0
  #     source:
  #         bower: {}
  - name: databrowser
    globalName: kbase-ui-plugin-databrowser
    version: 1.0.1
    cwd: src/plugin
    source:
      bower: {}
  - name: typebrowser
    globalName: kbase-ui-plugin-typebrowser
    version: 1.0.2
    cwd: src/plugin
    source:
      bower: {}
  - name: datawidgets
    globalName: kbase-ui-plugin-datawidgets
    version: 0.4.2
    cwd: src/plugin
    source:
      bower: {}
  - name: data-landing-pages
    globalName: kbase-ui-plugin-data-landing-pages
    version: 0.8.0
    cwd: src/plugin
    source:
      bower: {}
  - name: shockbrowser
    globalName: kbase-ui-plugin-shockbrowser
    version: 0.2.0
    cwd: src/plugin
    source:
      bower: {}
  - name: jobbrowser
    globalName: kbase-ui-plugin-jobbrowser
    version: 0.3.5
    cwd: src/plugin
    source:
      bower: {}
  - name: methodview
    globalName: kbase-ui-plugin-methodview
    version: 1.1.0
    cwd: src/plugin
    source:
      bower: {}
  - name: ontology-widgets
    globalName: kbase-ui-plugin-ontology-widgets
    version: 1.0.4
    cwd: src/plugin
    source:
      bower: {}
  - name: sdk-clients-test
    globalName: kbase-ui-plugin-sdk-clients-test
    version: 0.1.0
    cwd: src/plugin
    source:
      bower: {}
  - name: auth2-client
    globalName: kbase-ui-plugin-auth2-client
    version: 1.3.9
    cwd: src/plugin
    source:
      bower: {}
  - name: user-profile
    globalName: kbase-ui-plugin-user-profile
    version: 1.5.1
    cwd: src/plugin
    source:
      bower: {}
  - name: pavel-demo
    globalName: kbase-ui-plugin-pavel-demo
    version: 0.1.2
    cwd: src/plugin
    source:
      bower: {}
  - name: test-dynamic-table-widget
    globalName: kbase-ui-plugin-test-dynamic-table-widget
    version: 0.1.2
    cwd: src/plugin
    source:
      bower: {}
  - name: tester
    globalName: kbase-ui-plugin-tester
    version: 0.1.2
    cwd: src/plugin
    source:
      bower: {}
  - name: jgi-search
    globalName: kbase-ui-plugin-jgi-search
    version: 0.35.3
    cwd: src/plugin
    source:
      bower: {}
  - name: feeds
    globalName: kbase-ui-plugin-feeds
    version: 0.9.1
    cwd: src/plugin
    source:
      bower: {}
  - name: example-gopherjs
    globalName: kbase-ui-plugin-example-gopherjs
    version: 0.2.0
    cwd: src/plugin
    source:
      bower: {}
  - name: simple-sample
    globalName: kbase-ui-plugin-simple-sample
    version: 0.1.3
    cwd: src/plugin
    source:
      bower: {}
  - name: staging-browser
    globalName: kbase-ui-plugin-staging-browser
    version: 0.1.2
    cwd: src/plugin
    source:
      bower: {}
  - name: catalog
    globalName: kbase-ui-plugin-catalog
    version: 1.2.15
    cwd: src/plugin
    source:
      bower: {}
  - name: narrative-finder
    globalName: kbase-ui-plugin-narrative-finder
    version: 0.1.2
    cwd: src/plugin
    source:
      bower: {}
  - name: data-search
    globalName: kbase-ui-plugin-data-search
    version: 0.19.12
    cwd: src/plugin
    source:
      bower: {}
  - name: ui-diagnostics
    globalName: kbase-ui-plugin-ui-diagnostics
    version: 0.1.0
    cwd: src/plugin
    source:
      bower: {}
  - name: narrative-info
    globalName: kbase-ui-plugin-narrative-info
    version: 1.1.4
    cwd: src/plugin
    source:
      bower: {}
  - name: test-lookup
    globalName: kbase-ui-plugin-test-lookup
    version: 0.1.1
    cwd: src/plugin
    source:
      bower: {}
  - name: report-viewer
    globalName: kbase-ui-plugin-report-viewer
    version: 0.1.3
    cwd: src/plugin
    source:
      bower: {}
  - name: ui-service
    globalName: kbase-ui-plugin-ui-service
    version: 0.5.0
    cwd: src/plugin
    source:
      bower: {}
  - name: public-search
    globalName: kbase-ui-plugin-public-search
    version: 0.13.6
    cwd: src/plugin
    source:
      bower: {}
  # -
  #     name: example-clojurescript
  #     globalName: kbase-ui-plugin-example-clojurescript
  #     version: 0.1.0
  #     cwd: src/plugins
  #     source:
  #         directory: {}
  # -
  #     name: profile-admin
  #     globalName: kbase-ui-plugin-profile-admin
  #     version: 0.1.0
  #     cwd: src/plugin
  #     source:
  #         directory: {}
  #     name: example-trr
  #     globalName: kbase-ui-plugin-example-trr
  #     version: 0.1.2
  #     cwd: src/plugins
  #     source:
  #         bower: {}
  - name: dashboard3
    globalName: kbase-ui-plugin-dashboard3
    version: 0.1.0
    cwd: src/plugin
    source:
      bower: {}
  - name: projects-mvp1
    globalName: kbase-ui-plugin-projects-mvp1
    version: 0.2.2
    cwd: src/plugin
    source:
      bower: {}
  - name: organizations
    globalName: kbase-ui-plugin-organizations
    version: 0.15.65
    cwd: src/plugin
    source:
      bower: {}
