# UI SErvices
---
ui:
  services:
    analytics: {}
    coreService: {}
    data: {}
    heartbeat: {}
    instrumentation: {}
    ko-component: {}
    notification: {}
    route: {}
    rpc: {}
    schema: {}
    session: {}
    type: {}
    userprofile: {}
    widget: {}
    # dynamic-service: {}
    menu:
      menus:
        hamburger:
          sections: 
            main:
              items:
                -
                  id: narrative
                  auth: true
                -
                  id: jgi-search
                  auth: true
            developer:
              items:   
                -
                  id: ui-service
                  auth: true
                - 
                  id: dashboard2
                  auth: true
                - 
                  id: dashboard3
                  auth: true
                -
                  id: test-lookup
                  auth: true
                -
                  id: narrative-info
                  auth: true  
                -
                  id: simple-sample
                  auth: true
                -
                  id: narrative-finder
                  auth: true
                -
                  id: staging-browser
                  auth: true
                -
                  id: example-gopherjs
                  auth: true
                -
                  id: tester
                  auth: true
                -
                  id: test_dynamic_table
                  auth: true
                -             
                  id: databrowser
                  auth: true
                -
                  id: typebrowser
                  auth: true
                -
                  id: shockbrowser
                  auth: true
                -
                  id: about-services
                  auth: true
            help:
              items:
                -
                  id: about
                  auth: false
                -
                  id: contact-kbase
                  auth: false
                -
                  id: help
                  auth: false
        sidebar:
          sections:
            main:
              items:
                -
                  id: dashboard
                  auth: true
                - 
                  id: projects-mvp1
                  auth: true
                  allow: [alpha]
                - 
                  id: public-search
                  auth: true
                -
                  id: appcatalog
                  auth: false
                -
                  id: search
                  auth: true
                -
                  id: jobbrowser
                  # The label can ovveride the label from the plugin here
                  label: Jobs
                  auth: true
                -
                  id: account
                  auth: true
                -
                  id: feeds
                  auth: true
                  allow: [alpha]

