## Welcome Panel
---
package:
    name: welcome
    title: Various UI Routes
    description: A welcome page
    type: legacy
services:
    # Set up a route to install that widget in the main body view
    route:
        routes:
            - path: bulk-ui
              component: views/DeprecatedBulkUI
    # Set up a menu item to invoke the path above
    menu:
        items:
            - name: about-kbase
              type: external
              uri: https://www.kbase.us/
              newWindow: true
              label: KBase
              icon: home
            - name: docs
              type: external
              uri: https://docs.kbase.us/
              newWindow: true
              label: Docs
              icon: file-text
            - name: help
              type: external
              uri: https://www.kbase.us/support
              newWindow: true
              label: Support
              icon: question
