deploy:
    id: kbase-ui
    target: /kb/deployment/services/kbase-ui
    environment:
    hostname:
    icon:
    name:
# Settings in support of the user interface
ui:
    images:
        spinner:
            url: /images/ajax-loader.gif
    constants:
        client_timeout: 900000
        # session_max_age: 5184000
        # service check is conducted at ui startup; all core services are contacted to fetch
        # the current version. This affects the startup experience so we need to use a gradation
        # of timeouts. the slow timeout will trigger a warning for the user, but the check will
        # continue, the hard timeout will cancel the requests. slow is 10 seconds, hard limit is 1 minute.
        service_check_timeouts: 
            slow: 10000
            hard: 60000
     # TODO: simply paths?
    paths:
        spa_root: '#'
        landing_pages: '#dataview/'
        # ws_browser: '#/ws'
        version_check: /narrative_version
        dashboard_metrics: /userMetrics
    # TODO: simply urls?
    urls:
        reset_password: https://gologin.kbase.us/ResetPassword
        status_page: http://kbase.us/internal/status
        submit_jira_ticket: https://atlassian.kbase.us/secure/CreateIssueDetails!init.jspa?pid=10200&issuetype=1&description=#Narrative%20version
        update_profile: https://gologin.kbase.us/account/UpdateProfile
    # backupCookie:
    #   domain: null
    #   enabled: false
    # Services are configured here...
    services:
        analytics:
            cookie:
                name: _ga
                domain: kbase.us
                # approx 2 years
                maxAge: 63072000
            google:
                hostname: null
                code: null
        session:
            cookie:
                maxAge: 5184000
                name: kbase_session
                backup:
                    name: kbase_session_backup
                    domain: null
                    enabled: false
            # The widget id of the current login widget; supplied by the
            # auth plugin.
            loginWidget: auth2_signin

        route:
            defaultRoute:
                redirect:
                    path: login
        heartbeat:
            interval: 500
        # dynamic-service:
        #     hardTtl: 3600000 # 1 min
        #     hotTtl:  18000000 # 5 min
    # Feature Switches are unique values (preferrably uuids) which indicate a single feature or
    # or group of features. The featureSwitch id may be used within code, kbase-ui or plugins, to 
    # disable or enable code features.
    # The feature switch must be registered here, and then asserted as enabled, if desired, in a deploy
    # configuration.
    # The presence of a feature switch within the deploy config indicates that that switch is "on". 
    # Code may check whether a feature is on or off.
    # If a feature is referenced without it being defined, an error is thrown.
    # Therefore integration testing is your friend.
    featureSwitches:
        available: 
            -
                # id: "7b04d4d5-51fd-4789-a4f7-196ddf66b682"
                id: orcid_auth_provider
                title: ORCiD auth provider
                description: The ORCiD auth provider is
            -
                # id: "e4aa4a8a-2c42-497e-85da-ff050e45ba13"
                id: system_alert_notification
                title: The New System Alert Notification
            -
                id: search_features
                title: Search over Genome Features
            -
                id: similar_genomes
                title: Similar Genomes Landing Page Widget
            -
                id: new_provenance_widget
                title: New Provenance Widget
        enabled: []
        disabled: []
# Primarily for output links for the docsite.
# TODO: merge with ui.outbound_links?
docsite:
    base_url: http://kbase.us
    host: kbase.us
    paths:
        about: /what-is-kbase
        contact: /contact-us
        browser_support: /supported-browsers
