---
name: PR to develop opened
on:
  push:
    branches:
      - feature-*
      - fix-*
jobs:
  test:
    uses: ./.github/workflows/reusable_test.yml
  build:
    needs: test
    uses: ./.github/workflows/reusable_build-push.yml
    with:
      name: '${{ github.event.repository.name }}'
      tags: '${{ github.ref_name }}'
      buildConfig: ci
    secrets: inherit